routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (session()->has('userLogged')) {
        if (session()->get('userLogged') != null) {
            return redirect()->route('dashboard');
        }
        return redirect()->route('login');
    }

    return redirect()->route('login');
});

Auth::routes();

Route::get('/not-found', 'HomeController@not_found')->name('notFound');
Route::group(['middleware' => 'isHaveToken'], function()
{
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::resource('users', 'UserController');
    Route::resource('guru', 'GuruController');
    Route::resource('kelas', 'KelasController');
    Route::resource('siswa', 'SiswaController');
    Route::resource('mapel', 'MapelController');
    Route::resource('jadwal', 'JadwalController');
    Route::resource('presensi', 'PresensiController');
    Route::resource('rekap', 'RekapController');
    Route::get('/account', 'AccountController@account')->name('account.index');
    Route::post('/account', 'AccountController@account_save')->name('account.store');
});

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $response = Http::withToken(session()->get('tokenUser'))
        ->get(env('REST_API_ENDPOINT').'/api/siswa');

        $dataResponse = json_decode($response);

        return view('siswa.index', [
            'dataSiswa' => $dataResponse
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $response = Http::withToken(session()->get('tokenUser'))->get(env('REST_API_ENDPOINT').'/api/siswa');
        $dataResponse = json_decode($response);

        $idkelas = Http::withToken(session()->get('tokenUser'))->get(env('REST_API_ENDPOINT').'/api/kelas');
        $idkelasResponse = json_decode($idkelas);

        return view('siswa.create', [
            'dataSiswa' => $dataResponse,
            'dataKelas' => $idkelasResponse->data
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $response = Http::withToken(session()->get('tokenUser'))->post(env('REST_API_ENDPOINT').'/api/siswa', [
            
            'nis' => $request->nis,
            'nama' => $request->nama,
            'gender' => $request->gender,
            'tempat_lahir' => $request->tempat_lahir,
            'tgl_lahir' => $request->tgl_lahir,
            'email' => $request->email,
            'nama_ortu' => $request->nama_ortu,
            'alamat' => $request->alamat,
            'phone_number' => $request->phone_number,
            'kelas_id' => $request->kelas_id,
        ]);

        $dataResponse = json_decode($response);
        if($dataResponse->status == false){
            foreach($dataResponse->message as $message){
                return redirect()->route('siswa.create')->with('warning', $message);
            }
        }

        return redirect()->route('siswa.index')->with('success', 'Data Berhasil Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $response = Http::withToken(session()->get('tokenUser'))->get(env('REST_API_ENDPOINT').'/api/siswa/'.$id);
        $dataResponse = json_decode($response);

        $idkelas = Http::withToken(session()->get('tokenUser'))->get(env('REST_API_ENDPOINT').'/api/kelas');
        $idkelasResponse = json_decode($idkelas);
        return view('siswa.edit', [
            'dataSiswa' => $dataResponse,
            'dataKelas' => $idkelasResponse->data,
            'genders' => ['laki-laki', 'perempuan']
        ]);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $response = Http::withToken(session()->get('tokenUser'))->put(env('REST_API_ENDPOINT').'/api/siswa/'.$id, [
            
            'nis' => $request->nis,
            'nama' => $request->nama,
            'gender' => $request->gender,
            'tempat_lahir' => $request->tempat_lahir,
            'tgl_lahir' => $request->tgl_lahir,
            'email' => $request->email,
            'nama_ortu' => $request->nama_ortu,
            'alamat' => $request->alamat,
            'phone_number' => $request->phone_number,
            'kelas_id' => $request->kelas_id,
        ]);

        $dataResponse = json_decode($response);
        if($dataResponse->status == false){
            foreach($dataResponse->message as $message){
                return redirect()->route('siswa.edit',  $id)->with('warning', $message);
            }
        }

        return redirect()->route('siswa.index')->with('success', 'Data Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Http::withToken(session()->get('tokenUser'))->delete(env('REST_API_ENDPOINT').'/api/siswa/'.$id);

        return redirect('siswa')->with('success', 'Data Berhasil dihapus');
    }
}

resources/views/siswa/create.blade.php
@extends('layouts/main-admin')

@section('title', 'Tambah Siswa')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">SISWA</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">Tambah Siswa</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        <div class="card-body">
            @include ('includes.flash')
            <form role="form" method="post" action="{{ route('siswa.store') }}">
                @csrf
                <div class="card-body">
                    <h4>Data Siswa</h4>
                    <div class="form-group">
                        <label for="exampleInputJK">Kelas</label>
                        <select class="form-control" name="kelas_id" id="kelas_id" required>
                            @foreach ($dataKelas as $data)
                            <option value="{{ $data->id }}">{{ $data->nama_kelas }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">NIS</label>
                        <input type="text" value="{{ old('nis') }}" class="form-control" name="Nis" id="nis"
                            placeholder="nis" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama</label>
                        <input type="text" class="form-control" name="nama" id="nama" placeholder="Nama"
                            value="{{ old('nama') }}" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Tempat Lahir</label>
                        <input type="text" class="form-control" name="tempat_lahir" id="tempat_lahir"
                            placeholder="Tempat Lahir" value="{{ old('tempat_lahir') }}" required>
                    </div>
                    <div class="form-group mb-5">
                        <label for="exampleInputPendidikanTerakhir">Tanggal Lahir</label>
                        <input type="text" class="form-control pull-right" id="datepicker" name="tgl_lahir"
                            placeholder="Tanggal Lahir" value="{{ old('tgl_lahir') }}" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Jenis Kelamin</label>
                        <select class="form-control" name="gender" id="gender" value="{{ old('gender') }}" required>
                            <option value="laki-laki">Laki-Laki</option>
                            <option value="perempuan">Perempuan</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPendidikanTerakhir">Nomor Telphone</label>
                        <input id="phone_number" type="number"
                            class="form-control form-control-user @error('phone_number') is-invalid @enderror"
                            name="phone_number" id="phoneValidation" placeholder="Nomor Handphone"
                            value="{{ old('phone_number') }}" required autocomplete="phone number"
                            style="-webkit-appearance: none;margin: 0;">
                        @error('phone_number')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Email</label>
                        <input type="email" class="form-control" name="email" id="email" placeholder="Email"
                            value="{{ old('email') }}" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama Orang Tua</label>
                        <input type="text" class="form-control" name="nama_ortu" id="nama_ortu"
                            placeholder="Nama Orang Tua" value="{{ old('nama_ortu') }}" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Alamat</label>
                        <textarea name="alamat" class="form-control" id="alamat" cols="30" rows="10"
                            placeholder="Alamat" value="{{ old('alamat') }}" required></textarea>
                    </div>
                    <div class="card-body">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.scripts')
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"
    integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(function () {
        //Date picker
        $('#datepicker').datepicker({
        autoclose: true
        })
    });
    $('#phoneValidation').on('keyup', function () {
        this.value = this.value.replace(/[^0-9]/gi, '')
      });
</script>
@endsection

resources/views/siswa/edit.blade.php
@extends('layouts/main-admin')

@section('title', 'Edit Siswa')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">SISWA</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">Edit Siswa</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        <div class="card-body">
            @include ('includes.flash')
            <form role="form" method="post" action="{{ route('siswa.update', $dataSiswa->data->id) }}">
                @csrf
                @method('put')
                <div class="card-body">
                    <h4>Data Siswa</h4>
                    <div class="form-group">
                        <label for="exampleInputJK">Kelas</label>
                        <select class="form-control" name="kelas_id" id="kelas_id" required>
                            @foreach ($dataKelas as $data)
                            @if ($data->id == $dataSiswa->data->kelas_id)
                            <option value="{{ $data->id }}">{{ $data->nama_kelas }}</option>
                            @else
                            <option value="{{ $data->id }}">{{ $data->nama_kelas }}</option>
                            @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">NIS</label>
                        <input type="text" class="form-control" name="nis" id="nis" value="{{ $dataSiswa->data->nis }}"
                            required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama</label>
                        <input type="text" class="form-control" name="nama" id="nama"
                            value="{{ $dataSiswa->data->nama }}" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Tempat Lahir</label>
                        <input type="text" class="form-control" name="tempat_lahir" id="tempat_lahir"
                            value="{{ $dataSiswa->data->tempat_lahir }}" required>
                    </div>
                    <div class="form-group mb-5">
                        <label for="exampleInputPendidikanTerakhir">Tanggal Lahir</label>
                        <input type="text" class="form-control pull-right" id="datepicker" name="tgl_lahir"
                            value="{{ date('d/m/Y' , strtotime($dataSiswa->data->tgl_lahir)) }}" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Jenis Kelamin</label>
                        <select class="form-control" name="gender" id="gender" required>
                            @foreach ($genders as $gender)
                            @if ($gender == $dataSiswa->data->gender)
                            <option value="{{ $gender }}">{{ ucfirst( $gender) }}</option>
                            @else
                            <option value="{{ $gender }}">{{ ucfirst( $gender) }}</option>
                            @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPendidikanTerakhir">Nomor Telphone</label>
                        <input id="phone_number" type="number"
                            class="form-control form-control-user @error('phone_number') is-invalid @enderror"
                            name="phone_number" id="phoneValidation" value="{{ $dataSiswa->data->phone_number }}"
                            required style="-webkit-appearance: none;margin: 0;">
                        @error('phone_number')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Email</label>
                        <input type="email" class="form-control" name="email" id="email"
                            value="{{ $dataSiswa->data->email }}" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama Orang Tua</label>
                        <input type="text" class="form-control" name="nama_ortu" id="nama_ortu"
                            value="{{ $dataSiswa->data->nama_ortu }}" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Alamat</label>
                        <textarea name="alamat" class="form-control" id="alamat" cols="30" rows="10"
                            value="{{ $dataSiswa->data->alamat }}" required></textarea>
                    </div>
                    <div class="card-body">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.scripts')
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"
    integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(function () {
        //Date picker
        $('#datepicker').datepicker({
        autoclose: true
        })
    });
    $('#phoneValidation').on('keyup', function () {
        this.value = this.value.replace(/[^0-9]/gi, '')
      });
</script>
@endsection

resources/views/siswa/index.blade.php
@extends('layouts/main-admin')

@section('title', 'Siswa')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">SISWA</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">Siswa</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        <div class="card-body">
            @include ('includes.flash')
            <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th width="40">NO</th>
                        <th>NIS</th>
                        <th>NAMA</th>
                        <th>JENIS KELAMIN</th>
                        <th>TTL</th>
                        <th width="120">AKSI</th>
                    </tr>
                </thead>
                <tbody>
                    @if ($dataSiswa->data != null)
                    @foreach ($dataSiswa->data as $key => $siswa)
                    <tr>
                        <td>{{ $key+1 }}</td>
                        <td>{{ $siswa->nis }}</td>
                        <td>{{ $siswa->nama }}</td>
                        <td>{{ ucfirst($siswa->gender) }}</td>
                        <td>{{ date('d-m-Y', strtotime($siswa->tgl_lahir)) }}</td>
                        <td class="text-center">
                            <a href="{{ route('siswa.edit', $siswa->id) }}">
                                <button class="btn btn-secondary" data-toggle="tooltip" data-placement="top"
                                    title="Ubah">
                                    <i class="fa fa-edit"></i>
                                </button>
                            </a>

                            <form action="/siswa/{{ $siswa->id }}" id="delete-siswa-{{ $siswa->id }}" method="post"
                                style="display: inline">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Hapus">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    @endif
                </tbody>
            </table>
        </div>
    </div>
</section>
@include ('includes.scripts')
<script type="text/javascript">
    $(document).ready(function(){
            $("#data-admin_length").append('<a  href="{{ route('siswa.create') }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
        });
</script>
@endsection

resources/views/siswa/show.blade.php
@extends('layouts/main-admin')

@section('title', 'Detail Siswa')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">SISWA</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Detail Siswa</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td>NIS</td>
                        <td>: #</td>
                    </tr>
                    <tr>
                        <td>TAHUN MASUK</td>
                        <td>: #</td>
                    </tr>
                    <tr>
                        <td>NAMA</td>
                        <td>: #</td>
                    </tr>
                    <tr>
                        <td>KELAS</td>
                        <td>: #</td>
                    </tr>
                    <tr>
                        <td>TTL</td>
                        <td>: #</td>
                    </tr>
                    <tr>
                        <td>JENIS KELAMIN</td>
                        <td>: #</td>
                    </tr>
                    <tr>
                        <td>NOMOR TELPHONE</td>
                        <td>: #</td>
                    </tr>
                    <tr>
                        <td>EMAIL</td>
                        <td>: #</td>
                    </tr>
                    <tr>
                        <td>NAMA ORANG TUA/WALI</td>
                        <td>: #</td>
                    </tr>
                    <tr>
                        <td>ALAMAT</td>
                        <td>: #</td>
                    </tr>
                </table>        
            </div>
        </div>
    </div>
</section>
@include ('includes.scripts')
@endsection