routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (session()->has('userLogged')) {
        if (session()->get('userLogged') != null) {
            return redirect()->route('dashboard');
        }
        return redirect()->route('login');
    }

    return redirect()->route('login');
});

Auth::routes();

Route::get('/not-found', 'HomeController@not_found')->name('notFound');
Route::group(['middleware' => 'isHaveToken'], function()
{
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::resource('users', 'UserController');
    Route::resource('guru', 'GuruController');
    Route::resource('kelas', 'KelasController');
    Route::resource('siswa', 'SiswaController');
    Route::resource('mapel', 'MapelController');
    Route::resource('jadwal', 'JadwalController');
    Route::resource('presensi', 'PresensiController');
    Route::resource('rekap', 'RekapController');
    Route::get('/account', 'AccountController@account')->name('account.index');
    Route::post('/account', 'AccountController@account_save')->name('account.store');
});

app/Http/Controllers/JadwalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Jadwal;
use App\Model\Kelas;
use App\Model\Mapel;
use App\Model\Account;
use App\Model\TahunAjaran;
use App\Model\Semester;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;

class JadwalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {               
        $responseJadwal = Http::withToken(session()->get('tokenUser'))->get(env('REST_API_ENDPOINT').'/api/jadwal');
        $dataResponseJadwal = json_decode($responseJadwal);
        
        // dd($dataResponseJadwal->data, session()->get('userLogged'));
        // for($i = 0; $i < $dataResponseJadwal->data; $i++){
        //     if(session()->get('userLogged')->type == "guru" && session()->get('userLogged')->id == $dataResponseJadwal->data[$i]->user_id){
        //     }
        // }
        return view('jadwal.index', [
            'dataJadwal' => $dataResponseJadwal,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $responseKelas = Http::withToken(session()->get('tokenUser'))->get(env('REST_API_ENDPOINT').'/api/kelas/');
        $responseMapel = Http::withToken(session()->get('tokenUser'))->get(env('REST_API_ENDPOINT').'/api/mapel/');
        $responseGuru = Http::withToken(session()->get('tokenUser'))->get(env('REST_API_ENDPOINT').'/api/guru/');

        $dataResponseGuru = json_decode($responseGuru);
        $dataResponseMapel = json_decode($responseMapel);
        $dataResponseKelas = json_decode($responseKelas);

        return view('jadwal.create',[
            'dataJadwal' => $this->index()->dataJadwal,
            'dataGuru' => $dataResponseGuru->data,
            'dataMapel' => $dataResponseMapel->data,
            'dataKelas' => $dataResponseKelas->data,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $response = Http::withToken(session()->get('tokenUser'))->post(env('REST_API_ENDPOINT').'/api/jadwal', [
            'kelas_id' => $request->kelas_id,
            'mapel_id' => $request->mapel_id,
            'guru_id' => $request->guru_id,
            'hari' => $request->hari,
            'jam_pelajaran' => $request->jam_pelajaran,
        ]);

        $dataResponse = json_decode($response);
        if($dataResponse->status == false){
            foreach($dataResponse->message as $msg){
                return redirect()->route('guru.edit')->with('warning', $msg);
            }
        }

        return redirect('jadwal')->with('success', 'Data Added Successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $responseJadwal = Http::withToken(session()->get('tokenUser'))->get(env('REST_API_ENDPOINT').'/api/jadwal/'.$id);

        $dataResponseJadwal = json_decode($responseJadwal);
        return view('jadwal.index', [
            'dataJadwal' => $dataResponseJadwal,
        ]); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $responseKelas = Http::withToken(session()->get('tokenUser'))->get(env('REST_API_ENDPOINT').'/api/kelas/');
        $responseMapel = Http::withToken(session()->get('tokenUser'))->get(env('REST_API_ENDPOINT').'/api/mapel/');
        $responseGuru = Http::withToken(session()->get('tokenUser'))->get(env('REST_API_ENDPOINT').'/api/guru/');

        $dataResponseGuru = json_decode($responseGuru);
        $dataResponseMapel = json_decode($responseMapel);
        $dataResponseKelas = json_decode($responseKelas);

        return view('jadwal.edit',[
            'dataJadwal' => $this->show($id)->dataJadwal,
            'dataGuru' => $dataResponseGuru->data,
            'dataMapel' => $dataResponseMapel->data,
            'dataKelas' => $dataResponseKelas->data,
            'dataHari' => ['senin','selasa','rabu','kamis','jumat','sabtu']
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $response = Http::withToken(session()->get('tokenUser'))->put(env('REST_API_ENDPOINT').'/api/jadwal/'.$id, [
            'kelas_id' => $request->kelas_id,
            'mapel_id' => $request->mapel_id,
            'guru_id' => $request->guru_id,
            'hari' => $request->hari,
            'jam_pelajaran' => $request->jam_pelajaran,
        ]);

        $dataResponse = json_decode($response);
        if($dataResponse->status == false){
            foreach($dataResponse->message as $msg){
                return redirect()->route('guru.edit')->with('warning', $msg);
            }
        }

        return redirect('jadwal')->with('success', 'Data Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $responseJadwal = Http::withToken(session()->get('tokenUser'))->delete(env('REST_API_ENDPOINT').'/api/jadwal/'.$id);

        $dataResponseJadwal = json_decode($responseJadwal);

        return redirect()->route('jadwal.index')-> with('success', 'Data Berhasil Dihapus'); 
    }
}

resources/views/jadwal/create.blade.php
@extends('layouts/main-admin')

@section('title', 'Tambah Jadwal')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">JADWAL</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">Tambah Jadwal</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        <div class="card-body">
            @include ('includes.flash')
            <form role="form" method="post" action="{{ route('jadwal.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputJK">Kelas</label>
                        <select class="form-control" name="kelas_id" id="kelas_id" required>
                            @foreach ($dataKelas as $data)
                            <option value="{{ $data->id }}">{{ $data->nama_kelas }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Mata Pelajaran</label>
                        <select class="form-control" name="mapel_id" id="mapel_id" required>
                            @foreach ($dataMapel as $data)
                            <option value="{{ $data->id }}">{{ $data->nama_mapel }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Guru Pengampu</label>
                        <select class="form-control" name="guru_id" id="guru_id" required>
                            @foreach ($dataGuru as $data)
                            <option value="{{ $data->id }}">{{ $data->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Hari</label>
                        <select class="form-control" name="hari" id="hari" required>
                            <option value="senin">Senin</option>
                            <option value="selasa">Selasa</option>
                            <option value="rabu">Rabu</option>
                            <option value="kamis">Kamis</option>
                            <option value="jumat">Jumat</option>
                            <option value="sabtu">Sabtu</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Jam Pelajaran</label>
                        <input type="text" class="form-control" name="jam_pelajaran" id="jam_pelajaran"
                            placeholder="ex: 07.00 - 08.40 WIB" required>
                    </div>
                    <div class="card-body">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.scripts')
@endsection

resources/views/jadwal/edit.blade.php
@extends('layouts/main-admin')

@section('title', 'Edit Jadwal')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">JADWAL</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">Edit Jadwal</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        <div class="card-body">
            @include ('includes.flash')
            <form role="form" method="post" action="{{ route('jadwal.update', $dataJadwal->data->id) }}"
                enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputJK">Kelas</label>
                        <select class="form-control" name="kelas_id" id="kelas_id" required>
                            @foreach ($dataKelas as $data)
                            @if ($data->id == $dataJadwal->data->kelas_id)
                            <option value="{{ $data->id }}" selected>{{ $data->nama_kelas }}</option>
                            @else
                            <option value="{{ $data->id }}">{{ $data->nama_kelas }}</option>
                            @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Mata Pelajaran</label>
                        <select class="form-control" name="mapel_id" id="mapel_id" required>
                            @foreach ($dataMapel as $data)
                            @if ($data->id == $dataJadwal->data->mapel_id)
                            <option value="{{ $data->id }}" selected>{{ $data->nama_mapel }}</option>
                            @else
                            <option value="{{ $data->id }}">{{ $data->nama_mapel }}</option>
                            @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Guru Pengampu</label>
                        <select class="form-control" name="guru_id" id="guru_id" required>
                            @foreach ($dataGuru as $data)
                            @if ($data->id == $dataJadwal->data->guru_id)
                            <option value="{{ $data->id }}" selected>{{ $data->nama }}</option>
                            @else
                            <option value="{{ $data->id }}">{{ $data->nama }}</option>
                            @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Hari</label>
                        <select class="form-control" name="hari" id="hari" required>
                            @foreach ($dataHari as $hari)
                            @if ($hari == $dataJadwal->data->hari)
                            <option value="{{ $hari }}" selected>{{ ucfirst($hari) }}</option>
                            @endif
                            <option value="{{ $hari }}">{{ ucfirst($hari) }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Jam Pelajaran</label>
                        <input type="text" class="form-control" name="jam_pelajaran" id="jam_pelajaran"
                            value="{{ $dataJadwal->data->jam_pelajaran }}" required>
                    </div>
                    <div class="card-body">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.scripts')
@endsection

resources/views/jadwal/index.blade.php
@extends('layouts/main-admin')

@section('title', 'Jadwal')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">JADWAL</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">Jadwal</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        <div class="card-body">
            @include ('includes.flash')

            <div class="mb-4">
                @foreach ($dataJadwal->data as $jadwal)
                    <p class="text-danger"><b>Guru</b> : {{ $jadwal->nama }}</p>
                    <p class="text-warning"><b>NIP</b> : {{ $jadwal->nip }}</p>
                    <p class="text-success"><b>Email</b> : {{ $jadwal->email }}</p>
                    @break
                @endforeach
            </div>

            <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th width="40">NO</th>
                        <th>MAPEL</th>
                        <th>KELAS</th>
                        <th>HARI</th>
                        <th>JAM PELAJARAN</th>
                        <th width="120">AKSI</th>
                    </tr>
                </thead>
                <tbody>
                    @if ($dataJadwal->data != null)
                    @foreach ($dataJadwal->data as $key => $jadwal)
                    <tr>
                        <td>{{ $key+1 }}</td>
                        <td>{{ $jadwal->nama_mapel }}</td>
                        <td>{{ $jadwal->nama_kelas }}</td>
                        <td>{{ ucfirst($jadwal->hari) }}</td>
                        <td>{{ $jadwal->jam_pelajaran }}</td>
                        <td class="text-center">
                            <a href="{{ route('presensi.index') }}">
                                <button class="btn btn-primary" data-toggle="tooltip" data-placement="top"
                                    title="Presensi">
                                    <i class="bi bi-check2-square"></i>
                                </button>
                            </a>

                            <a href="{{ route('jadwal.edit', $jadwal->id) }}">
                                <button class="btn btn-secondary" data-toggle="tooltip" data-placement="top"
                                    title="Ubah">
                                    <i class="fa fa-edit"></i>
                                </button>
                            </a>

                            <form action="/jadwal/{{ $jadwal->id }}" id="delete-jadwal-{{ $jadwal->id }}" method="post"
                                style="display: inline">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Hapus">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    @endif
                </tbody>
            </table>
        </div>
    </div>
</section>
@include ('includes.scripts')
<script type="text/javascript">
    $(document).ready(function(){
            $("#data-admin_length").append('<a  href="{{ route('jadwal.create') }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
        });
</script>
@endsection

resources/views/jadwal/show.blade.php
@extends('layouts/main-admin')

@section('title', 'Detail Jadwal')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">JADWAL</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Detail Jadwal</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <div class="card-body">
                <table class="table">                    
                    <tr>
                        <td>KELAS</td>
                        <td>: </td>
                    </tr>
                    <tr>
                        <td>GURU PENGAMPU</td>
                        <td>: </td>
                    </tr>
                    <tr>
                        <td>MATA PELAJARAN</td>
                        <td>: </td>
                    </tr>
                    <tr>
                        <td>HARI</td>
                        <td>: </td>
                    </tr>
                    <tr>
                        <td>JAM PELAJARAN</td>
                        <td>: </td>
                    </tr>                                                           
                </table>   
                <hr>
                <h4>Data Siswa</h4>     
                <table class="table">
                    <thead>
                        <tr>
                            <th>NO</th>
                            <th>NIS</th>
                            <th>NAMA</th>
                            <th>JENIS KELAMIN</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{-- looping data siswa --}}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
@include ('includes.scripts')
@endsection